#region Copyright & License

// Copyright © 2024-2025 Yuma
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using System;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Yuma.Ddd;

/// <summary>Represents an exception that is thrown when a specified entity cannot be found.</summary>
/// <remarks>
/// This exception is typically used in scenarios where an operation is attempted on an entity that does not exist in the
/// underlying data store or context.
/// </remarks>
[SuppressMessage("ReSharper", "MemberCanBeInternal", Justification = "Public API.")]
public class EntityNotFoundException : Exception
{
	/// <summary>Throws an <see cref="EntityNotFoundException"/> if the specified entity is null.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessageFactory">
	/// Optional function to generate a custom error message providing additional context about the
	/// missing entity.
	/// </param>
	/// <exception cref="EntityNotFoundException">
	/// Thrown when the specified <paramref name="entity"/> is null. The exception message
	/// will include the message generated by the optional <paramref name="memberMessageFactory"/> if provided.
	/// </exception>
	[SuppressMessage("ReSharper", "MemberCanBeInternal", Justification = "Public API.")]
	public static void ThrowIfNull<TEntity>([NotNull] TEntity? entity, Func<string>? memberMessageFactory)
		where TEntity : Entity
	{
		ThrowIfNull(entity, memberMessageFactory?.Invoke());
	}

	/// <summary>Throws an <see cref="EntityNotFoundException"/> if the specified entity is null.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessage">Optional custom message providing additional context about the missing entity.</param>
	/// <exception cref="EntityNotFoundException">
	/// Thrown when the specified <paramref name="entity"/> is null. The exception message
	/// will include the optional <paramref name="memberMessage"/> if provided.
	/// </exception>
	[SuppressMessage("ReSharper", "MemberCanBeInternal", Justification = "Public API.")]
	public static void ThrowIfNull<TEntity>([NotNull] TEntity? entity, string? memberMessage = null)
		where TEntity : Entity
	{
		if (entity is not null) return;
		Throw(entity, memberMessage);
	}

	/// <summary>Throws an <see cref="EntityNotFoundException"/> for the specified entity type with an optional custom message.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessageFactory">
	/// Optional function to generate a custom error message providing additional context about the
	/// missing entity.
	/// </param>
	/// <exception cref="EntityNotFoundException">
	/// Thrown when the specified <paramref name="entity"/> is null. The exception message
	/// will include the message generated by the optional <paramref name="memberMessageFactory"/> if provided.
	/// </exception>
	[SuppressMessage("ReSharper", "MemberCanBePrivate.Global", Justification = "Public API.")]
	[SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required for generic type resolution.")]
	[SuppressMessage("ReSharper", "UnusedParameter.Global", Justification = "Required for generic type resolution.")]
	public static void Throw<TEntity>([NotNull] TEntity? entity, Func<string>? memberMessageFactory)
		where TEntity : Entity
	{
		Throw(entity, memberMessageFactory?.Invoke());
	}

	/// <summary>Throws an <see cref="EntityNotFoundException"/> for the specified entity type with an optional custom message.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessage">Optional custom message providing additional context about the missing entity.</param>
	/// <exception cref="EntityNotFoundException">
	/// Always thrown, indicating that an entity of the specified type could not be found. If
	/// the <paramref name="memberMessage"/> is provided, it will be included in the exception message.
	/// </exception>
	[SuppressMessage("ReSharper", "MemberCanBePrivate.Global", Justification = "Public API.")]
	[SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Required for generic type resolution.")]
	[SuppressMessage("ReSharper", "UnusedParameter.Global", Justification = "Required for generic type resolution.")]
	public static void Throw<TEntity>([NotNull] TEntity? entity, string? memberMessage = null)
		where TEntity : Entity
	{
		var builder = new StringBuilder().Append("Entity '")
			.Append(typeof(TEntity).Name);
		if (memberMessage is not null)
			builder.Append(" { ")
				.Append(memberMessage)
				.Append(" }");
		builder.Append("' not found.");
		throw new EntityNotFoundException(builder.ToString());
	}

	/// <summary>Initializes a new instance of the <see cref="EntityNotFoundException"/> class with default values.</summary>
	/// <remarks>Use this constructor when no specific message or inner exception needs to be provided.</remarks>
	[SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Public API.")]
	public EntityNotFoundException() { }

	/// <summary>Initializes a new instance of the <see cref="EntityNotFoundException"/> class with a specified error message.</summary>
	/// <param name="message">A message that describes the error.</param>
	/// <remarks>Use this constructor to provide a specific error message that gives more context about the missing entity.</remarks>
	[SuppressMessage("ReSharper", "MemberCanBePrivate.Global", Justification = "Public API.")]
	public EntityNotFoundException(string message) : base(message) { }

	/// <summary>
	/// Initializes a new instance of the <see cref="EntityNotFoundException"/> class with a specified error message and a
	/// reference to the inner exception that caused this exception.
	/// </summary>
	/// <param name="message">A message that describes the error.</param>
	/// <param name="innerException">
	/// The exception that is the cause of the current exception, or <see langword="null"/> if no inner
	/// exception is specified.
	/// </param>
	/// <remarks>Use this constructor to capture additional details about the underlying cause of the exception.</remarks>
	[SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Public API.")]
	public EntityNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
