#region Copyright & License

// Copyright © 2024 - 2025 Yuma
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using System;
using System.Diagnostics.CodeAnalysis;

namespace Yuma.Ddd.Extensions;

[SuppressMessage("ReSharper", "MemberCanBeInternal", Justification = "Public API.")]
[SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Public API.")]
public static class EntityExtensions
{
	/// <summary>Throws an <see cref="EntityNotFoundException"/> if the specified entity is null.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessageFactory">
	/// Optional function to generate a custom error message providing additional context about the
	/// missing entity.
	/// </param>
	/// <exception cref="EntityNotFoundException">
	/// Thrown when the specified <paramref name="entity"/> is null. The exception message
	/// will include the message generated by the optional <paramref name="memberMessageFactory"/> if provided.
	/// </exception>
	[return: NotNull]
	public static TEntity UnlessEntityIsNotFound<TEntity>([NotNull] this TEntity? entity, Func<string>? memberMessageFactory)
		where TEntity : Entity
	{
		EntityNotFoundException.ThrowIfNull(entity, memberMessageFactory);
		return entity;
	}

	/// <summary>Throws an <see cref="EntityNotFoundException"/> if the specified entity is null.</summary>
	/// <typeparam name="TEntity">The type of the entity derived from the base Entity class.</typeparam>
	/// <param name="entity">The entity to be checked for null. Must be of a type derived from Entity.</param>
	/// <param name="memberMessage">Optional custom message providing additional context about the missing entity.</param>
	/// <exception cref="EntityNotFoundException">
	/// Thrown when the specified <paramref name="entity"/> is null. The exception message
	/// will include the optional <paramref name="memberMessage"/> if provided.
	/// </exception>
	[return: NotNull]
	public static TEntity UnlessEntityIsNotFound<TEntity>([NotNull] this TEntity? entity, string? memberMessage = null)
		where TEntity : Entity
	{
		EntityNotFoundException.ThrowIfNull(entity, memberMessage);
		return entity;
	}
}
